### PR TITLE
Feature/database

### PR DESCRIPTION
**Pull request by pedrolorandi**

### CODE REVIEW

**Comment by binding1** [comment]
Line 67 on schema.prisma shows the following:

amount_decimal Int

Any reason it's an integer and not a decimal/float data type?

Also I think having more than 1 user and having different seeds for that user may be helpful in case we do want to move forward with OAuth or some sort of authentication.

**Comment by pedrolorandi** [comment]
Integer operations in JavaScript are generally faster and more accurate than floating-point operations.

I thought we could use one user for now, and update the seeds based on necessity, if it's okay with you.

**Comment by binding1** [comment]
Sure, we can go with one user for now then.

I see, but it still seems like it makes sense to use decimal for the amounts field since transactions are realistically going to have cents. Are we using integers strictly for dev purposes?

**Comment by binding1** [comment]
Ok makes sense. Should be good to merge.

**Pull request merged**
